Repository a5chin/refrigerator, pull requests merged in 2023-07, with the labels that each got.

#1 Backend structure decisions
  backend/air.toml
  backend/build.sh
  backend/config/config.yaml
  backend/config/definition.go
  backend/controller/ingredient.go
  backend/controller/interfaces.go
  backend/docs/docs.go
  backend/docs/swagger.json
  backend/docs/swagger.yaml
  backend/entity/errors.go
  backend/entity/ingredient.go
  backend/go.mod
  backend/go.sum
  backend/infrastructure/driver/database.go
  backend/infrastructure/driver/token.go
  backend/infrastructure/middleware/transaction.go
  backend/infrastructure/repogitory/ingredient.go
  backend/infrastructure/repogitory/model/ingredient.go
  backend/main.go
  backend/usecase/ingredient.go
  backend/usecase/interfaces.go
  docker-compose.yml
  docker/backend.Dockerfile
  docker/mysql.Dockerfile
  mysql/my.conf
  mysql/sql/create.sql
  mysql/sql/insert.sql
Labels: question

#2 PR、issueテンプレートの作成
  .github/ISSUE_TEMPLATE/task.md
  .github/PULL_REQUEST_TEMPLATES.md
Labels: documentation

#4 データベースの更新と食品取得 API の修正
  backend/controller/ingredient.go
  backend/controller/interfaces.go
  backend/docs/docs.go
  backend/docs/swagger.json
  backend/docs/swagger.yaml
  backend/entity/ingredient.go
  backend/infrastructure/repogitory/ingredient.go
  backend/infrastructure/repository/ingredient.go
  backend/infrastructure/repository/model/ingredient.go
  backend/main.go
  backend/usecase/ingredient.go
  backend/usecase/interfaces.go
  mysql/sql/create.sql
  mysql/sql/insert.sql
Labels: bug

#5 5 大栄養素の取得 API
  backend/controller/interfaces.go
  backend/controller/nutrition.go
  backend/docs/docs.go
  backend/docs/swagger.json
  backend/docs/swagger.yaml
  backend/entity/nutrition.go
  backend/infrastructure/repository/model/nutrition.go
  backend/infrastructure/repository/nutrition.go
  backend/main.go
  backend/usecase/interfaces.go
  backend/usecase/nutrition.go
  mysql/sql/create.sql
  mysql/sql/insert.sql
Labels: enhancement

#8 frontend の消去
  frontend/.gitignore
Labels: enhancement
